# name: {{project_name}}
name: "f"
description: {{project_description}}
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  vector_graphics: ^1.1.19
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  dio_refresh_bot: ^2.2.1
  easy_localization: ^3.0.8
  freezed_annotation: ^3.1.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_flavorizr: ^2.4.1
  freezed: ^3.2.3

  vector_graphics_compiler: ^1.1.19
  flutter_gen_runner: ^5.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/l10n/
    - assets/images/
    - path: assets/svgIcons/
      transformers:
        - package: vector_graphics_compiler
    - assets/icons/



flutter_gen:
  output: lib/utils/gen/
