name: {{project_name}}
# name: "testNameToDelete"
description: {{project_description}}
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  vector_graphics: ^1.1.19
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  dio_refresh_bot: ^2.2.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  easy_localization: ^3.0.8
  freezed_annotation: ^3.1.0
  flutter_screenutil: ^5.9.3
  get_it: ^9.2.0
  go_router: ^17.0.0
  injectable: ^2.7.1
  flutter_timezone: ^5.0.1
  google_fonts: ^6.3.2
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  timezone: ^0.10.1
  vibration: ^3.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_flavorizr: ^2.4.1
  freezed: ^3.2.3
  vector_graphics_compiler: ^1.1.19
  flutter_gen_runner: ^5.12.0
  injectable_generator: ^2.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/l10n/
    - assets/images/
    - path: assets/svgIcons/
      transformers:
        - package: vector_graphics_compiler
    - assets/icons/



# # dart run flutter_flavorizr
# flavorizr:
#   flavors:
#     stage:
#       app:
#         name: "App Stage"
#         package_name: "{{stage_package_name}}"
#       android:
#         applicationId: "{{stage_package_name}}"
#     production:
#       app:
#         name: "App Production"
#         package_name: "{{production_package_name}}"
#       android:
#         applicationId: "{{production_package_name}}"
#   instructions:
#     - android:androidManifest
#     - android:flavorizrGradle
#     - android:buildGradle
#     - flutter:flavors
#     - ide:config

flutter_gen:
  output: lib/utils/gen/
